# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: ehentai_py37_ubuntu_x86_64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.5.1
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.0.9/waifu2x_vulkan-1.0.9-cp37-cp37m-linux_x86_64.whl
        if [ -f requirements.txt ]; then pip install -r src/requirements.txt; fi
    - name: Build
      run: |
        cd src
        pyinstaller -F -w start.py
        mv dist ehentai
        tar -zcvf ${{ env.PACKAGENAME }}.tar.gz ehentai/
        mv ${{ env.PACKAGENAME }}.tar.gz ..
        cd ..
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.tar.gz
        retention-days: 7

  macos:
    runs-on: macos-latest
    env:
      PACKAGENAME: ehentai_py37_macos_x86_64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.5.1
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.0.9/waifu2x_vulkan-1.0.9-cp37-cp37m-macosx_10_14_x86_64.whl
        pip install -r src/requirements.txt
        brew install create-dmg
    - name: Build
      run: |
        cd src
        cp ../res/icon/Icon.icns ./
        pyinstaller --clean --onedir --name Ehentai \
            --hidden-import waifu2x_vulkan --hidden-import PySide6 --hidden-import requests \
            --hidden-import urllib3 --hidden-import websocket-client --hidden-import pillow \
            --hidden-import config \
            --hidden-import component \
            --hidden-import server \
            --hidden-import task \
            --hidden-import tools \
            --hidden-import view \
            --strip --windowed -i Icon.icns \
            start.py
        rm -rf dist/Ehentai
        cp Icon.icns dist/
        ln -s /Applications/   dist/Applications
        create-dmg --volname "Ehentai" --volicon "Icon.icns" --icon "Icon.icns" 200 190 \
            --hide-extension "Icon.icns" ${{ env.PACKAGENAME }}.dmg dist/
        zip -9 ehentai.zip ${{ env.PACKAGENAME }}.dmg
        mv ${{ env.PACKAGENAME }}.dmg ..
        mv ehentai.zip ..
        cd ..
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ehentai.zip
        retention-days: 7
        
  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: ehentai_py37_windows_x64
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==4.5.1
        pip install https://github.com/tonquer/waifu2x-vulkan/releases/download/v1.0.9/waifu2x_vulkan-1.0.9-cp36.cp37.cp38.cp39.cp310-none-win_amd64.whl
        pip install -r src\requirements.txt
    - name: Build
      run: |
        cd src
        cp ..\res\icon\icon.ico .\
        pyinstaller -F -i icon.ico start.py
        mv dist/start.exe "dist/start(debug).exe"
        pyinstaller -F -w -i icon.ico start.py
        mv dist ehentai
        cp ..\LICENSE ehentai\
        cp ..\CHANGELOG ehentai\
        cd ..
        mkdir ${{ env.PACKAGENAME }}
        mv src\ehentai ${{ env.PACKAGENAME }}
        7z a -r "$($Env:PACKAGENAME + '.zip')" "ehentai"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}
        retention-days: 7